# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches:
    - master
    - dev

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
env:
  DOCKER_USER: ${{ secrets.DOCKER_USERNAME }}
  JAR_VAR: 1.0.0


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: git checkout 
        uses: actions/checkout@v3
      
      - name: update version
        working-directory: my-app/
        run: |
          version=$(cat pom.xml | grep "<version>" | head -n 1 | awk -F '[<>]' '{print $3}')
          echo -e "version = $version"
          new_version=$(echo $version | awk -F '.' '{print $1 "." $2 "." $3 + 1}')
          mvn versions:set -DnewVersion="$new_version"
          echo $new_version > version.txt

          
      - uses: mr-smithers-excellent/docker-build-push@v5
        name: Build & push Docker image
        with:
          image: $DOCKER_USER/hello
          tags: $(cat my-app/version.txt), latest
          registry: docker.io
          dockerfile: my-app/Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: commit files to repo
        working-directory: my-app/
        run: |
          git config --local user.name secrets.GITHUB_USERNAME
          git config --local user.email secrets.GITHUB_USEREMAIL
          git add pom.xml
          git commit -m "update project to $(cat version.txt)"
      
      - name: run container
        run: docker run omerag/hello:latest

      - name: push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}